### ISSUE TITLE
"ImportError: cannot import name 'protobuf' from 'lib'" while trying to run Assets/main.py

### ISSUE THREAD

**Issue by denliner** [nobbyfix/AzurLaneTools#8]
Hi, 
Sorry to bother you, but I got this error message when I tried to run the asset downloader and extractor:

```
Traceback (most recent call last):
  File "XXX:\XXX\AzurLaneTools\Assets\main.py", line 5, in <module>
    from lib import config, protobuf, versioncontrol, updater, repair
ImportError: cannot import name 'protobuf' from 'lib' (XXX:\XXX\AzurLaneTools\Assets\lib\__init__.py)
```
At first I thought that something hadn't gone as planned during dependencies installation so I re-installed all of them + google's  'protobuf' but I still had that error message.
So I decided to check the "Assets/lib" folder and I noticed that there [was no "protobuf" file or folder ](https://github.com/nobbyfix/AzurLaneTools/tree/master/Assets/lib). After some digging I found that there was indeed a 'protobuf' folder but it has been removed after commit ```e570fcd```

I'm wondering if I've missed a step

**System:**

- OS: Windows 11
- Python version: 3.10

**Additional context:**
None.

**Comment by nobbyfix** [comment]
asset downloader is moved to another repo with full functionality added
